# Generated by Django 4.2.3 on 2023-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Turno A"),
                            ("B", "Turno B"),
                            ("C", "Turno C"),
                            ("D", "Turno D"),
                            ("E", "Turno E"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                        verbose_name=" (Obligatorio) Turno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, default=None, null=True)),
                (
                    "prize",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("player", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
