# Generated by Django 4.2.3 on 2023-09-19 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loto", "0002_alter_prize_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prize",
            old_name="prize",
            new_name="amount",
        ),
    ]
